pub mod ai_commands;
pub mod app_commands;
pub mod clean_commands;
pub mod entry_commands;
pub mod import_commands;
pub mod knowledge_commands;
pub mod performance_commands;
pub mod relation_commands;
pub mod search_commands;
